In [11]:
import pandas as pd
import numpy as np

In [12]:
df1 = pd.read_excel(r'C:\Users\WAKU\Documents\ANTONIO_BOZA\DATA_WAKU\EXPRESS\PLANILLAS VIGENTES DE SM 2019-2020_REV_18-02.xlsx')
df2 = pd.read_excel(r'C:\Users\WAKU\Documents\ANTONIO_BOZA\DATA_WAKU\EXPRESS\Maracaibo_Z_Rev_18-02.xlsx')

In [13]:
df1.head()

,CONTRIBUYENTE,RIF,TELEFONO,RIM,AÑO,CONCEPTO,FECHA LIQ,FECHA VENC,SOLICITUD,MONTO,ESTATUS,PARROQUIA,DIRECCION-1
0,CENTRO DE DIAG C Y RADIOL JESUS DE NAZARENO C.A.,312967358,2.610000e+02,2900011642,2020,Pago por Servicios Municipales,2020-02-07,2020-02-29,754554,1.205324e+08,VIGENTE,FRANCISCO EUGENIO BUSTAMANTE ...,Parroquia FRANCISCO EUGENIO BUSTAMANTE Sector ...
1,CLINICA SUCRE C.A,70133082,2.610000e+02,2000072525,2020,Pago por Servicios Municipales,2020-02-10,2020-02-29,761332,1.205324e+08,VIGENTE,CHIQUINQUIRA ...,Parroquia CHIQUINQUIRA Sector LA LIMPIA Avenid...
2,CENTRO MEDICO DE OCCIDENTE C A,70003359,2.617960e+09,2000082649,2020,Pago por Servicios Municipales,2020-02-10,2020-02-29,752333,1.203477e+08,VIGENTE,OLEGARIO VILLALOBOS ...,Parroquia OLEGARIO VILLALOBOS Sector SANTA RIT...
3,"BIONALISTAS ASOCIADAS, C.A.",301805429,4.140000e+02,7000001567,2020,Pago por Servicios Municipales,2020-02-06,2020-02-29,749135,1.169918e+08,VIGENTE,BOLIVAR ...,Parroquia BOLIVAR Sector 5 DE JULIO Avenida 14...
4,MEDLAB C.A,311725415,1.000000e+00,2900000607,2020,Pago por Servicios Municipales,2020-02-06,2020-02-29,749141,1.169918e+08,VIGENTE,OLEGARIO VILLALOBOS ...,Parroquia OLEGARIO VILLALOBOS Sector SAN MARTI...

In [14]:
df2.head()

,RNUM,TIPO CONTRIB,RIF,RAZON_SOCIAL,CORREO,ACTIVIDAD_ECONOMICA,TELEFONOS,DIRECCION,NOMBRE_ESTADO,MUNICIPIO,TIPO_CONTRIBUYENTE
0,25,C,295867549,"INVERSIONES LOPEZ & TETE, C.A,",ALBERTOTETEDIAZ@HOTMAIL.COM,NaN,"0261-8149356, NO INDICA","AVENIDA 78 ENTRE CALLES 65B Y 65D, SECTOR BARR...",ZULIA,MARACAIBO,CONTRIBUYENTE ORDINARIO
1,29,C,295990626,"COOPERATIVA BANCO COMUNAL LA PIONERA,R.L.,",MARINA.RODRIGUEZ.63@HOTMAIL.COM,NaN,"0261-7786021, NO INDICA","AVENIDA 108B-01 CON CALLE APURE, URBANIZACION ...",ZULIA,MARACAIBO,CONTRIBUYENTE ORDINARIO
2,31,C,296063680,"PROTECCION TIUNA.C,A,,",LILLYRANGEL@HOTMAIL.COM,NaN,"NO INDICA, 0414-9634941","AVENIDA 2D, SECTOR BARRIO PUNTICA DE PIEDRA, C...",ZULIA,MARACAIBO,CONTRIBUYENTE ORDINARIO
3,39,C,296223190,COOPERATIVA BANCO COMUNAL INDIGENA NUCHONYUU...,CCJUYA@GMAIL.COM,NaN,"0000-0000000, NO INDICA","CARRETERA MARA VIA LA CONCEPCION, SECTOR LA GA...",ZULIA,MARACAIBO,CONTRIBUYENTE ORDINARIO
4,48,C,296496480,ASOCIACION COOP BANCO COMUNAL COUTAJIRRAJENA W...,CCICOUTAJIRRAENAWAYAAWANEPIA@GMAIL.COM,NaN,"0000-0000000, NO INDICA","CALLE 29, SECTOR BRR CATATUMBO, CASA NRO 28-71...",ZULIA,MARACAIBO,CONTRIBUYENTE ORDINARIO

In [15]:
df1_no_duplic = df1.drop_duplicates(subset = "RIF", keep = "first")

In [16]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3673 entries, 0 to 3672
Data columns (total 13 columns):
CONTRIBUYENTE    3672 non-null object
RIF              3673 non-null int64
TELEFONO         3671 non-null float64
RIM              3660 non-null object
AÑO              3673 non-null int64
CONCEPTO         3673 non-null object
FECHA LIQ        3673 non-null datetime64[ns]
FECHA VENC       3673 non-null datetime64[ns]
SOLICITUD        3673 non-null int64
MONTO            3673 non-null float64
ESTATUS          3673 non-null object
PARROQUIA        3673 non-null object
DIRECCION-1      3671 non-null object
dtypes: datetime64[ns](2), float64(2), int64(3), object(6)
memory usage: 373.2+ KB

In [17]:
df1_no_duplic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3230 entries, 0 to 3672
Data columns (total 13 columns):
CONTRIBUYENTE    3229 non-null object
RIF              3230 non-null int64
TELEFONO         3229 non-null float64
RIM              3219 non-null object
AÑO              3230 non-null int64
CONCEPTO         3230 non-null object
FECHA LIQ        3230 non-null datetime64[ns]
FECHA VENC       3230 non-null datetime64[ns]
SOLICITUD        3230 non-null int64
MONTO            3230 non-null float64
ESTATUS          3230 non-null object
PARROQUIA        3230 non-null object
DIRECCION-1      3229 non-null object
dtypes: datetime64[ns](2), float64(2), int64(3), object(6)
memory usage: 353.3+ KB

In [18]:
df1_nd_df2 = pd.merge(left = df1_no_duplic, right = df2, on = None, left_on = 'RIF', right_on = 'RIF')

In [19]:
df1_nd_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3311 entries, 0 to 3310
Data columns (total 23 columns):
CONTRIBUYENTE          3310 non-null object
RIF                    3311 non-null int64
TELEFONO               3310 non-null float64
RIM                    3302 non-null object
AÑO                    3311 non-null int64
CONCEPTO               3311 non-null object
FECHA LIQ              3311 non-null datetime64[ns]
FECHA VENC             3311 non-null datetime64[ns]
SOLICITUD              3311 non-null int64
MONTO                  3311 non-null float64
ESTATUS                3311 non-null object
PARROQUIA              3311 non-null object
DIRECCION-1            3310 non-null object
RNUM                   3311 non-null int64
TIPO CONTRIB           3311 non-null object
RAZON_SOCIAL           3311 non-null object
CORREO                 3311 non-null object
ACTIVIDAD_ECONOMICA    3265 non-null object
TELEFONOS              3311 non-null object
DIRECCION              3311 non-null object
NOMBRE_ESTADO          3311 non-null object
MUNICIPIO              3311 non-null object
TIPO_CONTRIBUYENTE     3311 non-null object
dtypes: datetime64[ns](2), float64(2), int64(4), object(15)
memory usage: 620.8+ KB

In [20]:
archivo_final = df1_nd_df2.to_excel('Consolidado_Planillas_Vs_Seniat_19-02.xlsx')